### PR TITLE
Add HTML_TAGNAME_TEXT_TRANSFORM to theme property

### PR DESCRIPTION
**Pull request by CodyReichert**
There is currently a [hard-coded `textTransform: lowercase` style](https://github.com/xyc/react-inspector/blob/master/src/styles/base.js#L11) in the default theme for tag names. This is problematic for XML documents that rely on uppercase tag names.

This PR adds `HTML_TAGNAME_TEXT_TRANSFORM` as a theme property so it can be overridden by users (and it maintains backwards compatibility by keeping the default as 'lowercase'.)

As an example, an SVG document can have a `linearGradient` tag. This library currently shows it as `lineargradient` (which, in XML, would be two different tags).

@xyc - does this look good to you? Curious if there was a reason you added 'lowercase'? I think we could remove this completely, but thought we might as well keep it as a theme property.

### CODE REVIEW

**Comment by CodyReichert** [comment]
Just to visualize what we're seeing in Assertible - the highlighted tag should be `linearGradient` not `lineargradient`:

image

**Comment by creichert** [comment]
@ndelangen, @xyc What do you think about this change? We're definitely interested in properly supporting case-sensitivity in the [Assertible](https://assertible.com) XML viewer.

**Comment by ndelangen** [comment]
My first gut feeling is to simply remove the CSS rule, I'm also curious why this is there?

1 reason might be that HTML is case INsensitive.. 

but  XML & JSX are not!

**Comment by kumarabhishek** [comment]
@creichert, can you provide example as how the change you are suggesting will help someone override text-transform behavior so that you get linearGradient. I might be wrong but I believe its tagName that should decide whether lineargradient or linearGradient should be displayed. We should not go by css-transform as any value that we set (capitalize, uppercase, lowercase, or none) will be applied for all tags not not any specific tag. How about removing css-transform if its not serving any specific purpose other than forcing all tag names to be in lowercase ?

**Comment by CodyReichert** [comment]
@ndelangen - I agree, my initial thought is to completely remove it as well. I didn't even think about JSX, but that's exactly right.

@kumarabhishek - It would basically look like this:
```js
import { chromeLight } from 'react-inspector'

<Inspector theme={{...chromeLight, ...({ HTML_TAGNAME_TEXT_TRANSFORM: 'none' })}} data={{...}}/>
```

but you are correct that it would apply for ALL tags in `data`, not just a specific one. Keep in mind that I'm  just making an _existing_ style overridable - I didn't change any default behavior here. I think you're correct that removing it is the best option.

---

I'm 100% in favor of getting rid of it, so thanks for all the input here guys. I'll give @xyc a bit to chime in and see if there was a reason for this,  otherwise I'll just remove it :100:

**Comment by xyc** [comment]
@CodyReichert LGTM. Good work! The reason I added `textTransform:lowercase` is that HTML Element tag names are by default uppercase, but browser devtool implementations displays lower case tags.

**Review by xyc — APPROVED** [review]

**Comment by CodyReichert** [comment]
Thanks @xyc (and everyone else for the input), that makes sense, so then it's good that I left the default behavior as is :1st_place_medal: 

I'm going to merge this and upload it as a new patch version `v2.1.3` since there are no breaking changes here.

**Pull request merged**
