### PR TITLE
Fix ObjectValue for given Object.create(null)

### LINKED ISSUE #48: TypeError: Cannot read property 'name' of undefined
Hi there.

So I'm trying to display an `EventEmitter` from `eventemitter3`, which has an internal property `_events` of type `Events`. This internal property does not have a `constructor`, so I'm getting an error on [this line](https://github.com/xyc/react-inspector/blob/master/src/object/ObjectValue.js#L59). I'd make a PR, but I actually don't know what the solution should be.

### PR DESCRIPTION
**Pull request by rivertam**
Fixes #48

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
You are a hero! 💥 

I will do a release tomorrow!

**Comment by rivertam** [comment]
Ping -- can we get a release ASAP? I mostly just use this for debugging, so no actual rush, but publishing a fork and using it is even more effort than just asking for a push. :)

**Comment by ndelangen** [comment]
I'm on it

**Comment by ndelangen** [comment]
Released as minor version!

**Pull request merged**
