### PR TITLE
Cast number to string Fixes #42

### LINKED ISSUE #42: Warning: Received NaN for numeric attribute `children`
React throws a warning for NaN, could be solved by using `{String(value)}` for numbers also, same as is used for boolean values.

```js
Warning: Received NaN for numeric attribute `children`. If this is expected, cast the value to a string.
    in span (created by ObjectValue)
    in ObjectValue (created by ObjectPreview)
    in ObjectPreview (created by ObjectRootLabel)
    in ObjectRootLabel (created by defaultNodeRenderer)
    in defaultNodeRenderer (created by TreeNode)
    in div (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by TreeView)
    in TreeView (created by ObjectInspector)
    in ThemeProvider (created by ObjectInspector)
    in ObjectInspector (created by Inspector)
    in Inspector
```

See #43

### PR DESCRIPTION
**Pull request by rhalff**

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Thank you @rhalff this looks good to me!

Would you want to help maintain this package?

**Comment by rhalff** [comment]
@ndelangen yeah, no problem :-)

**Comment by ndelangen** [comment]
@xyc Can you invite @rhalff to collaborate on this repo? 🙇 

Or provide me with administrator rights so I can do this myself?

**Comment by ndelangen** [comment]
Published as `2.2.2`

**Comment by xyc** [comment]
@ndelangen Added @rhalff, thanks for the PR!

**Pull request merged**
