### PR TITLE
Fix react peer dep

### PR DESCRIPTION
**Pull request by majapw**
Hi there!

There's a typo in the peer dep requirement for this package which is causing some downstream errors. I've addressed the change here. :)

### CODE REVIEW

**Comment by ndelangen** [comment]
Has this been released yet?

**Comment by CodyReichert** [comment]
@ndelangen - it has not. The package is still on 2.2.0 and this was merged after that. Releasing this as 2.2.1 would be great.

@majapw - thanks for the fix!

**Comment by ndelangen** [comment]
Will release a new version tomorrow!

**Comment by ndelangen** [comment]
DONE! 🚀

**Pull request merged**
