### PR TITLE
Support react 17 as a peer dependency

### PR DESCRIPTION
**Pull request by bcomnes**
Getting peer dependency warnings from this package.  Everything appears to still work though.

### CODE REVIEW

**Comment by bcomnes** [comment]
Any chance for a quick review/merge/release?  Would help a lot downstream on issues with npm 7 peer dep changes.

**Comment by bcomnes** [comment]
Happy new year! Any chance we can review this? Thank you!  🙏

**Review by Hypnosphi — APPROVED** [review]

**Comment by Hypnosphi** [comment]
@ndelangen can you please release it?

**Comment by bcomnes** [comment]
Awesome thank you ! ❤️

**Pull request merged**
