### PR TITLE
Add showMaxKeys to truncate long iterables

### PR DESCRIPTION
**Pull request by olizilla**
I needed a mechanism to avoid showing the user super long arrays, as it was chewing out alot of render time, and as they were file Buffers of bytes, not super informative. 

I've added a `showMaxKeys` prop to ObjectInspector to set the max number of keys to enumerate and an `isMeta` prop on ObjectLabel to format the truncation info.

screenshot 2018-07-03 18 04 11

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by xyc** [comment]
Ideally we would want the inspector to match how browsers look like.

Do you only want it for arrays or other objects as well? In chrome, arrays are segmented into groups of 100, which appears to be a better experience for me.

**Comment by olizilla** [comment]
I need it for anything with a lot of keys as the perf and UX drops significantly with out it. 

Truncating works for my needs. Please feel free to take this PR as a starting point.

**Comment by ndelangen** [comment]
I'd be happy with truncated as well, even if long-term we'd want as @xyc is suggesting.

Can we proceed with this PR?

**Comment by ndelangen** [comment]
@olizilla I added a better CI, could you maybe see if you could resolve the merge conflicts with this feedback?

**Comment by olizilla** [comment]
I'm not going to get time soon to push this forwards. Please feel free to adopt this branch or close it out.

**Pull request closed without merging**
