### PR TITLE
Fixes for v3

### PR DESCRIPTION
**Pull request by xyc**
Hey guys @ndelangen @xadn, I have made a few fixes before v3.0.0 release of this library. The major feature of v3 is @xadn's hook/new context API pr (#68, #69).

This PR fixes:
- `<ol>` as root dom element (#53)
- Support for null prototypes (integrate #65)
- Make max objects in preview a theme variable (follow up on #67)
- Styling to make it more look like Chrome recent versions
    - function shows up as a single char `ƒ`
    - if `object.constructor.name` is `Object`, don't show `Object` in the preview.
Old: `▶Object {...}` New: `▶{...}`
    - Arrays preview `▶ (20) {...}`
- Some minor refactors

I'm intending other features in the backlog to be in a future release: [detailed preview](https://developers.google.com/web/updates/2017/05/devtools-release-notes#object-previews) and long iterables #58, so that they could be implemented in a proper and extensible way.

### CODE REVIEW

**Comment by xyc** [comment]
@ndelangen I've setup netlify deploy previews to build storybooks, please let me know if it works for you. I'm taking this opportunity to learn netlify :-) so not transferring this to an org yet. Happy to move this repo to an org (Storybooks?) if it make more sense in maintaining this.

**Comment by xyc** [comment]
Closed as fixed in #70

**Comment by xyc** [comment]
@ndelangen @xadn this is published as v3.0.0 (with a note on readme) Thanks so much!

**Comment by ndelangen** [comment]
@xyc yeah I'm open to moving this repo under the storybook github org if you are, I'll invite you to the storybook org, so you can transfer.

**Comment by xyc** [comment]
@ndelangen just transferred, thanks!

**Comment by xyc** [comment]
@ndelangen I don't have admin / settings access to this repo now, do you mind taking a look?

**Pull request merged**
